# Generated by Django 5.2.1 on 2025-07-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrun',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
