# Generated by Django 5.2.1 on 2025-07-31 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0002_reviewrun_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_question_chars', models.IntegerField(default=5000)),
                ('methodology_chars', models.IntegerField(default=5000)),
                ('findings_chars', models.IntegerField(default=5000)),
                ('gaps_chars', models.IntegerField(default=5000)),
                ('max_tokens_compose', models.IntegerField(default=1500)),
                ('max_tokens_edit', models.IntegerField(default=1500)),
            ],
        ),
    ]
