# Generated by Django for WritingStyleFile model
from django.db import migrations, models
import os

def writing_style_upload_path(instance, filename):
    return os.path.join('writing_style', filename)

class Migration(migrations.Migration):
    dependencies = [
        ('rag_app', '0003_appsettings'),
    ]
    operations = [
        migrations.CreateModel(
            name='WritingStyleFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=writing_style_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
