# Generated by Django 5.2.1 on 2025-08-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0004_writingstylefile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writingstylefile',
            old_name='name',
            new_name='original_name',
        ),
        migrations.AlterField(
            model_name='writingstylefile',
            name='file',
            field=models.FileField(upload_to='writing_styles/'),
        ),
        migrations.AlterField(
            model_name='writingstylefile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
