# Generated by Django 5.2.1 on 2025-08-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0005_rename_name_writingstylefile_original_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='writing_style_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
