# Generated by Django 5.2.1 on 2025-08-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0006_appsettings_writing_style_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='writing_style_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
